(in-package #:conserv.http)

(defvar *request*)

(defprotocol request-event-driver (a)
  ((data ((driver a) data)
    :default-form nil)
   (continue ((driver a))
    :default-form nil)
   (upgrade ((driver a) data)
    :default-form (close *request* :abort t))
   (close ((driver a))
    :default-form nil))
  (:prefix on-request-))

(defprotocol request (a)
  ((state ((request a)) :accessorp t)
   (method ((request a)) :accessorp t)
   (url ((request a)) :accessorp t)
   (headers ((request a)) :accessorp t)
   #+nil(trailers ((request a)))
   (http-version ((request a)) :accessorp t)
   (external-format ((request a)) :accessorp t)
   (request-parser ((request a)))
   (http-server ((reply a)))
   (keep-alive-p ((reply a)) :accessorp t)
   (socket ((request a))))
  (:prefix request-))

(defclass request ()
  ((method :initform nil :accessor request-method)
   (url :accessor request-url)
   (headers :accessor request-headers)
   (http-version :accessor request-http-version)
   (external-format :initarg :external-format :accessor request-external-format)
   (request-parser :initform (make-request-parser) :reader request-request-parser)
   (http-server :reader request-http-server :initarg :http-server)
   (keep-alive-p :accessor request-keep-alive-p :initform t)
   (state :accessor request-state :initform :headers)
   (socket :initarg :socket :reader request-socket)))
